/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package triliumapp;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class DashboardFormGuru extends javax.swing.JFrame {

   int xx,xy;
    public DashboardFormGuru() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new triliumapp.custom.customPanel();
        customPanel2 = new triliumapp.custom.customPanel();
        dashboardImg = new javax.swing.JLabel();
        Dashboardtxt = new javax.swing.JLabel();
        customPanel3 = new triliumapp.custom.customPanel();
        courseImg = new javax.swing.JLabel();
        coursetxt = new javax.swing.JLabel();
        customPanel4 = new triliumapp.custom.customPanel();
        bookingImg = new javax.swing.JLabel();
        bookingtxt = new javax.swing.JLabel();
        customPanel5 = new triliumapp.custom.customPanel();
        searchImg = new javax.swing.JLabel();
        searchtxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customPanel7 = new triliumapp.custom.customPanel();
        mainpn = new triliumapp.custom.customPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        customPanel1.setBackground(new java.awt.Color(255, 255, 255));
        customPanel1.setRoundBottomLeft(20);
        customPanel1.setRoundBottomRight(20);
        customPanel1.setRoundTopLeft(20);
        customPanel1.setRoundTopRight(20);

        customPanel2.setBackground(new java.awt.Color(255, 255, 255));
        customPanel2.setRoundBottomLeft(10);
        customPanel2.setRoundBottomRight(10);
        customPanel2.setRoundTopLeft(10);
        customPanel2.setRoundTopRight(10);

        dashboardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Home unclicked.png"))); // NOI18N
        dashboardImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardImgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardImgMouseExited(evt);
            }
        });

        Dashboardtxt.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        Dashboardtxt.setForeground(new java.awt.Color(102, 255, 255));
        Dashboardtxt.setText("Dashboard");
        Dashboardtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout customPanel2Layout = new javax.swing.GroupLayout(customPanel2);
        customPanel2.setLayout(customPanel2Layout);
        customPanel2Layout.setHorizontalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardImg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        customPanel2Layout.setVerticalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dashboardtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customPanel3.setBackground(new java.awt.Color(255, 255, 255));
        customPanel3.setRoundBottomLeft(10);
        customPanel3.setRoundBottomRight(10);
        customPanel3.setRoundTopLeft(10);
        customPanel3.setRoundTopRight(10);

        courseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/course unclicked.png"))); // NOI18N
        courseImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseImgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courseImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courseImgMouseExited(evt);
            }
        });

        coursetxt.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        coursetxt.setForeground(new java.awt.Color(102, 255, 255));
        coursetxt.setText("Course");
        coursetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursetxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coursetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coursetxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout customPanel3Layout = new javax.swing.GroupLayout(customPanel3);
        customPanel3.setLayout(customPanel3Layout);
        customPanel3Layout.setHorizontalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(courseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        customPanel3Layout.setVerticalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(courseImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coursetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customPanel4.setBackground(new java.awt.Color(255, 255, 255));
        customPanel4.setRoundBottomLeft(10);
        customPanel4.setRoundBottomRight(10);
        customPanel4.setRoundTopLeft(10);
        customPanel4.setRoundTopRight(10);

        bookingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/booking uncliked.png"))); // NOI18N
        bookingImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingImgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingImgMouseExited(evt);
            }
        });

        bookingtxt.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        bookingtxt.setForeground(new java.awt.Color(102, 255, 255));
        bookingtxt.setText("Create");
        bookingtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout customPanel4Layout = new javax.swing.GroupLayout(customPanel4);
        customPanel4.setLayout(customPanel4Layout);
        customPanel4Layout.setHorizontalGroup(
            customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookingImg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        customPanel4Layout.setVerticalGroup(
            customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookingImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customPanel5.setBackground(new java.awt.Color(255, 255, 255));
        customPanel5.setRoundBottomLeft(10);
        customPanel5.setRoundBottomRight(10);
        customPanel5.setRoundTopLeft(10);
        customPanel5.setRoundTopRight(10);

        searchImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Search uncliked.png"))); // NOI18N
        searchImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchImgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchImgMouseExited(evt);
            }
        });

        searchtxt.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        searchtxt.setForeground(new java.awt.Color(102, 255, 255));
        searchtxt.setText("Search");
        searchtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout customPanel5Layout = new javax.swing.GroupLayout(customPanel5);
        customPanel5.setLayout(customPanel5Layout);
        customPanel5Layout.setHorizontalGroup(
            customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchImg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        customPanel5Layout.setVerticalGroup(
            customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Close");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        customPanel7.setBackground(new java.awt.Color(83, 86, 255));
        customPanel7.setRoundBottomLeft(20);
        customPanel7.setRoundBottomRight(20);

        mainpn.setBackground(new java.awt.Color(83, 86, 255));
        mainpn.setRoundBottomLeft(20);
        mainpn.setRoundBottomRight(20);
        mainpn.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout customPanel7Layout = new javax.swing.GroupLayout(customPanel7);
        customPanel7.setLayout(customPanel7Layout);
        customPanel7Layout.setHorizontalGroup(
            customPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpn, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        customPanel7Layout.setVerticalGroup(
            customPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpn, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(customPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addComponent(customPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)))
                .addGap(24, 24, 24)
                .addComponent(customPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
     
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x -xx, y -xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void DashboardtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardtxtMouseEntered
        Dashboardtxt.setForeground(new Color(83,86,255));
        dashboardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Home.png")));
    }//GEN-LAST:event_DashboardtxtMouseEntered

    private void DashboardtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardtxtMouseExited
        Dashboardtxt.setForeground(new Color(102,255,255));
        dashboardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Home unclicked.png")));
    }//GEN-LAST:event_DashboardtxtMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       LoginForm lf = new LoginForm();
       lf.setVisible(true);
       lf.revalidate();
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void coursetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursetxtMouseEntered
        coursetxt.setForeground(new Color(83,86,255));
        courseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/course.png")));
    }//GEN-LAST:event_coursetxtMouseEntered

    private void coursetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursetxtMouseExited
        coursetxt.setForeground(new Color(102,255,255));
        courseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/course unclicked.png")));
    }//GEN-LAST:event_coursetxtMouseExited

    private void bookingtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingtxtMouseEntered
        bookingtxt.setForeground(new Color(83,86,255));
        bookingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/booking.png")));
    }//GEN-LAST:event_bookingtxtMouseEntered

    private void bookingtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingtxtMouseExited
        bookingtxt.setForeground(new Color(102,255,255));
        bookingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/booking uncliked.png")));
    }//GEN-LAST:event_bookingtxtMouseExited

    private void searchtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxtMouseEntered
        searchtxt.setForeground(new Color(83,86,255));
        searchImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Search.png")));
    }//GEN-LAST:event_searchtxtMouseEntered

    private void searchtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxtMouseExited
        searchtxt.setForeground(new Color(102,255,255));
        searchImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Search uncliked.png")));
    }//GEN-LAST:event_searchtxtMouseExited

    private void dashboardImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardImgMouseEntered
       Dashboardtxt.setForeground(new Color(83,86,255));
        dashboardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Home.png")));
    }//GEN-LAST:event_dashboardImgMouseEntered

    private void dashboardImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardImgMouseExited
        Dashboardtxt.setForeground(new Color(102,255,255));
        dashboardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Home unclicked.png")));
    }//GEN-LAST:event_dashboardImgMouseExited

    private void courseImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseImgMouseEntered
         coursetxt.setForeground(new Color(83,86,255));
        courseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/course.png")));
    }//GEN-LAST:event_courseImgMouseEntered

    private void courseImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseImgMouseExited
      coursetxt.setForeground(new Color(102,255,255));
        courseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/course unclicked.png")));
    }//GEN-LAST:event_courseImgMouseExited

    private void bookingImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingImgMouseEntered
       bookingtxt.setForeground(new Color(83,86,255));
        bookingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/booking.png")));
    }//GEN-LAST:event_bookingImgMouseEntered

    private void bookingImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingImgMouseExited
        bookingtxt.setForeground(new Color(102,255,255));
        bookingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/booking uncliked.png")));
    }//GEN-LAST:event_bookingImgMouseExited

    private void searchImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchImgMouseEntered
         searchtxt.setForeground(new Color(83,86,255));
        searchImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Search.png")));
    }//GEN-LAST:event_searchImgMouseEntered

    private void searchImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchImgMouseExited
        searchtxt.setForeground(new Color(102,255,255));
        searchImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triliumapp/image/Search uncliked.png")));
    }//GEN-LAST:event_searchImgMouseExited

    private void coursetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursetxtMouseClicked
       mainpn.removeAll();
       mainpn.add(new CourseMain());
       mainpn.revalidate();
        
    }//GEN-LAST:event_coursetxtMouseClicked

    private void DashboardtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardtxtMouseClicked
       mainpn.removeAll();
       mainpn.add(new dashboardMain());
       mainpn.revalidate();
    }//GEN-LAST:event_DashboardtxtMouseClicked

    private void bookingtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingtxtMouseClicked
       mainpn.removeAll();
       mainpn.add(new createCourseMain());
       mainpn.revalidate();
    }//GEN-LAST:event_bookingtxtMouseClicked

    private void searchtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxtMouseClicked
        mainpn.removeAll();
       mainpn.add(new SearchMain());
       mainpn.revalidate();
    }//GEN-LAST:event_searchtxtMouseClicked

    private void dashboardImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardImgMouseClicked
        mainpn.removeAll();
       mainpn.add(new dashboardMain());
       mainpn.revalidate();
    }//GEN-LAST:event_dashboardImgMouseClicked

    private void courseImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseImgMouseClicked
       mainpn.removeAll();
       mainpn.add(new CourseMain());
       mainpn.revalidate();
    }//GEN-LAST:event_courseImgMouseClicked

    private void bookingImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingImgMouseClicked
         mainpn.removeAll();
       mainpn.add(new createCourseMain());
       mainpn.revalidate();
    }//GEN-LAST:event_bookingImgMouseClicked

    private void searchImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchImgMouseClicked
        mainpn.removeAll();
       mainpn.add(new SearchMain());
       mainpn.revalidate();
    }//GEN-LAST:event_searchImgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFormGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboardtxt;
    private javax.swing.JLabel bookingImg;
    private javax.swing.JLabel bookingtxt;
    private javax.swing.JLabel courseImg;
    private javax.swing.JLabel coursetxt;
    private triliumapp.custom.customPanel customPanel1;
    private triliumapp.custom.customPanel customPanel2;
    private triliumapp.custom.customPanel customPanel3;
    private triliumapp.custom.customPanel customPanel4;
    private triliumapp.custom.customPanel customPanel5;
    private triliumapp.custom.customPanel customPanel7;
    private javax.swing.JLabel dashboardImg;
    private javax.swing.JLabel jLabel1;
    private triliumapp.custom.customPanel mainpn;
    private javax.swing.JLabel searchImg;
    private javax.swing.JLabel searchtxt;
    // End of variables declaration//GEN-END:variables
}
